[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
json5 = "0.4"
chrono = "0.4"
shared = { path = "../shared" }
anyhow = "1.0"
